### ISSUE TITLE
Add MIT License 

### ISSUE THREAD

**Issue by nspangler** [gadicc/meteor-reactive-window#11]
Could you please add an MIT license to the README. I would love to implement your package into my production application but need it covered by the MIT license first to do so. You can copy and paste from here :  [simple schema license](https://github.com/aldeed/meteor-simple-schema/blob/v1/LICENSE.md)  . Thanks!

**Comment by gadicc** [comment]
hey @nspangler, sorry for the delay, been travelling.  The package is now MIT licensed, thanks for pointing this out.

**Comment by nspangler** [comment]
@gadicc thank you for the quick response and the awesome package!
