### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by monbro** [gadicc/meteor-reactive-window#2]
It would be awesome to add to the readme the snippet I can use to add the plugin to meteor? `meteor add gadicc:meteor-reactive-window` does not work unfortunately :-/

**Comment by gadicc** [comment]
@monbro, sorry, it's a bit embarrassing that you wrote this in December and I'm only replying now.  I was away without internet then and didn't notice it, please accept my apologies.

I've added the correct line to the README.  In general you should know that a lot of meteor projects are named `meteor-*` on github, and their package name (for installation via the meteor package server) will be without this prefix.

Thanks for your patience and happy coding!

**Comment by monbro** [comment]
Don't worry! I think this addition could be useful for other meteor newbies in case they stumble upon your package via Github as well. Thanks for adding!
