### ISSUE TITLE
Firefox first update

### ISSUE THREAD

**Issue by der-ede** [gadicc/meteor-reactive-window#4]
Hi there,

just want to say thank you for the package. On Google Chrome it works perfectly, on Firefox the values are not updated on initial pageload (maybe the 100msec in your lazyUpdate are too short for Firefox, idunno).
On changing the windowsize it is ok then.

But I figured it works with 
```Javascript
Template.name.rendered = function() {
  rwindow.forceUpdate();
}
```

**Comment by mellors** [comment]
Mobile Safari has the same problem. @der-ede thanks for your solution, works here as well. @gadicc IMHO this should be mentioned in the readme

**Comment by gadicc** [comment]
Thanks @der-ede and @mellors; sorry for the late reply and glad you found a workaround while my attention was elsewhere.

I think the problem is actually that we were setting the initial value too late.  Can you try `v1.0.5` and see if it makes any difference?

**Comment by steph643** [comment]
It works for me on Chrome and Firefox with 1.0.5. (not tested with previous versions, though).

**Comment by gadicc** [comment]
Sounds good to me :)
